name: PR Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache .pnpm-store
        uses: actions/cache@v1
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install pnpm
        run: |
          npm i -g pnpm@6
          pnpm set verify-store-integrity false
      - name: pnpm install
        run: |
          pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm run build

      - name: Lint types and code
        run: pnpm run lint

      - name: Run tests
        run: pnpm test

      - name: Run e2e tests
        run: pnpm e2e
